FROM php:7.2-alpine

MAINTAINER Peter Lai <alk03073135@gmail.com>

COPY composer-setup.php composer-setup.php
# COPY php.ini-production $PHP_INI_DIR/php.ini

RUN apk update && \
    apk add git

# Install gmp
Run apk add gmp-dev && \
    docker-php-ext-install gmp

# Install nodejs
# Run apk add --update nodejs nodejs-npm
RUN apk add --no-cache libzip-dev && docker-php-ext-configure zip --with-libzip=/usr/include && docker-php-ext-install zip

# Install composer
#RUN php docker/php/composer-setup.php && \
#    php docker/php/composer-setup.php --install-dir=/usr/bin --filename=composer && \
#    php -r "unlink('docker/php/composer-setup.php');"

#WORKDIR /app
